Algoritmo "Ex-1-04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   vp, vl: inteiro
Inicio
    escreva("Informe o valor do litro da gasolina: ")
    leia(vl)
    escreva("Qual sera o valor a ser pago? ")
    leia(vp)
    
    escreva("Você conseguis colocar ",vp\vl, " litros no seu tanque")
Fimalgoritmo