Algoritmo "Ex-1-11"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/07/2021
Var
   f: inteiro
Inicio
      escreva("Type the tempetature in Fahrenheit degree (°F): ")
      leia(f)
      escreva("the tempetature in Celsius degree(°C) will be : ",5*(f-32)/9)
Fimalgoritmo