Algoritmo "Ex-1-18"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2021
Var
   n:inteiro
Inicio
      escreva("Enter a number: ")
      leia(n)
      se ((n%2=0) e (n<10))entao
         escreva("MEETS THE CONDITIONS")
      senao
           escreva("DON'T MEETS THE CONDITIONS")
      fimse

Fimalgoritmo