Algoritmo "Ex-1-17"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/07/2021
Var
   c: inteiro
Inicio
      escreva("Type the code: ")
      leia(c)
      se (c=1)entao
         escreva("Aguarde")
      fimse
      se (c=2)entao
         escreva("Siga")
      fimse
Fimalgoritmo