Algoritmo "Ex-1-19"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2021
Var
   n1,n2,soma: inteiro
Inicio
      escreva("Type two numbers: ")
      leia(n1,n2)
      soma<- n1+n2
      se (soma%2=0)entao
         escreva("It's even")
      senao
           escreva("It's odd")
      fimse
Fimalgoritmo