Algoritmo "Ex-1-03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   x,y,a: inteiro
Inicio
      escreva("Type the values: ")
      leia(x,y)
      a<-x
      x<-y
      y<-a
      escreval("X: ",x)
      escreval("Y: ",y)
Fimalgoritmo