Algoritmo "Ex-1-08"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   b,h: real
Inicio
      escreva("Enter with the values of base: ")
      leia(b)
      escreva("Enter with the values of height: ")
      leia(h)
      escreva("The area value is: ",b*h)
Fimalgoritmo