Algoritmo "Ex-1-09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var

Inicio
   escreval("The media of 7,8 e 9 is: ",(7+8+9)/3)
   escreval("The media of 4,5 e 6 is: ",(4+5+6)/3)
   escreval("The medias sum is: ",((7+8+9)/3)+((4+5+6)/3))
   escreval("The medias media is: ",(((7+8+9)/3)+((4+5+6)/3))/2)
Fimalgoritmo