Algoritmo "Ex-1-01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/07/2021
Var
   n : inteiro
Inicio
      escreva("Enter a number: ")
      leia(n)
      escreval("O seu antecessor é: ",n-1)
      escreval("O seu sucessor é: ",n+1)
Fimalgoritmo