Algoritmo "Ex-1-26"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2021
Var
   d,r:real
Inicio
      escreva("Valor de receita: ")
      leia(r)
      escreva("Valor da despesa: ")
      leia(d)
      se (r-d > 0)entao
         escreva("Foi lucro")
      senao
           escreva("Foi prejuízo")
      fimse

Fimalgoritmo