Algoritmo "Ex-1-06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   vb,ve,vn : inteiro
Inicio
      vb<-10000
      escreva("Type the opened value: ")
      leia(ve)
      vn<-vb+ve
      escreva("The bank have: ",vn)
Fimalgoritmo