Algoritmo "Ex-1-07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   vv,s: real
Inicio
      escreva("What was the sale value: ")
      leia(vv)
      s<- 75000+(vv*15/100)
      escreva("Your salary will be: ",s)
Fimalgoritmo