Algoritmo "Ex-1-27"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2021
Var
 a: inteiro

Inicio
      escreva("Type a number: ")
      leia(a)

      se ((a>19)e(a<91))entao
         escreva("Is in the range")
      senao
           escreva("Isn't in the range")
      fimse
Fimalgoritmo