Algoritmo "Ex-1-14"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/07/2021
Var
   n: inteiro
Inicio
      escreva("Type a number: ")
      leia(n)
      se(n>0)entao
          escreva("Este número é positivo")
      senao
          escreva("Este número não é positivo")
      fimse
Fimalgoritmo