Algoritmo "Ex-1-13"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/07/2021
Var
   v,d: inteiro
Inicio
      escreva("Win amount: ")
      leia(v)
      escreva("Lose amount: ")
      leia(d)
      se (v>d)entao
         escreva("GOOD")
      fimse
      se(v<d)entao
         escreva("Bad")
      fimse
Fimalgoritmo