Algoritmo "Ex-2-12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/07/2021
Var
   s,i:inteiro
Inicio
      para i<-86 ate 907 passo 2 faca
           s<-s+i
           escreval(i)
      fimpara
      escreval("Sum",s)
Fimalgoritmo