Algoritmo "Ex-2-25"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/07/2021
Var
   n1,n2,s,i: inteiro
Inicio
      escreva("Type a first value: ")
      leia(n1)
      escreva("Type a secund value: ")
      leia(n2)
      para i<-n1 ate n2 faca
           s<-s+i
      fimpara
      escreva("Sum: ",s)
Fimalgoritmo