Algoritmo "Ex-2-01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/07/2021
Var
   n: inteiro
Inicio
      repita
            escreva("Type a number: ")
            leia(n)
            escreval(n^2)
      ate(n%6=0)
Fimalgoritmo