Algoritmo "Ex-2-24"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2021
Var
   i: inteiro
   n,s: real
Inicio
      para i<-1 ate 10 faca
           escreva("Enter a number: ")
           leia(n)
           se (n<40)entao
              s<-s+n
           fimse
      fimpara
      escreva("Sum < 40 is: ",s)
Fimalgoritmo